// <auto-generated />
namespace WorkoutAnalytics.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeworkoutdescforeignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeworkoutdescforeignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201906120336469_remove-workout-desc-foreignkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
