// <auto-generated />
namespace WorkoutAnalytics.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usernameuniqueness : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usernameuniqueness));
        
        string IMigrationMetadata.Id
        {
            get { return "201906120519549_username-uniqueness"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
